name: CI

on:
  push:
    branches: [ 4.x ]
  pull_request:
    branches: [ 4.x ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      version: '8, 10, 12, 14, 16, 18, 20, 22'
