name: CI

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  Job:
    name: Node.js
    uses: node-modules/github-actions/.github/workflows/node-test.yml@master
    with:
      version: '12, 14, 16, 18, 20'
